# -*- coding: utf-8 -*-
"""Advanced Netflix Case Study.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z_0EeXHajzHZp51je_OWAMBJQzclJboX
"""

#Importing all the required libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("/content/netflix.csv")
df.head()

df.shape

for i in df.columns:
  print(str(i)," : ",str(df[i].nunique()))

"""From the above we can observe all show_id's and titles are unique so need to check if any duplicated rows are there"""

df.info()

"""If we observe all columns expect release_year are of object datatype"""

df.isnull().sum()

"""If we observe columns like director,cast,country has more null values

So we cant drop rows containing nulls in those columns

And also it is not appropriate to impute those columns with some metric(like most frequent category) so let us fill them with empty string
"""

df['director']=df['director'].fillna("")
df['cast']=df['cast'].fillna("")
df['country']=df['country'].fillna("")

df.isnull().sum()

"""Now we have very less number of rows with null values so we will drop them"""

df=df.dropna()
df.head()

df.shape

date_format = '%B %d, %Y'

# Check if the date strings match the format
df['is_valid_date'] = pd.to_datetime(df['date_added'], format=date_format, errors='coerce').notna()

df['is_valid_date'].all()

"""So if we observe all date_added columns in the given format"""

df[~(df['is_valid_date'])]

"""So there are 88 rows with date added column not matching required format.This can be due to trailing white spaces so we try to remove them and check"""

df['date_added']=df['date_added'].apply(lambda x:x.strip())
date_format = '%B %d, %Y'

# Check if the date strings match the format
df['is_valid_date'] = pd.to_datetime(df['date_added'], format=date_format, errors='coerce').notna()
df['is_valid_date'].all()

"""Now all values in date_added column are in required format so we convert into that required format"""

date_format = '%B %d, %Y'
df['date_added'] = pd.to_datetime(df['date_added'], format=date_format)
df.head()

df.drop(['is_valid_date'],axis=1,inplace=True)
df.head()

df.dtypes

"""So now let us drop columns show-id,title and description because they may not add any value to our analysis"""

df.drop(columns=['title','description','show_id'],inplace=True)
df.head()

"""If we observe have columns like cast have multiple values for each movie/show beacause one or more person can be acted in a movie/show.So we can convert that into list of names and also we can convert all names into lower case and remove trailing space

Similary we repeat this procedure for listed_in column
"""

df['cast']=df['cast'].apply([lambda x:[i.strip().lower() for i in x.split(",") if i!=""]])
df['listed_in']=df['listed_in'].apply([lambda x:[i.strip().lower() for i in x.split(",") if i!=""]])
df.head()

"""There can be possibilty that that one movie can be directed by one more directors"""

df['director'].apply(lambda x:"," in x).any()

df.loc[df['director'].apply(lambda x:"," in x)]

"""So if we observe there are 614 rows that contain more than one director for movie/show"""

df['director']=df['director'].apply([lambda x:[i.strip().lower() for i in x.split(",") if i!=""]])
df.head()

"""Similarly some movies/shows are produced by multiple countries

"""

df['country'].apply(lambda x:"," in x).any()

df['country']=df['country'].apply([lambda x:[i.strip().lower() for i in x.split(",") if i!=""]])
df.head()

def get_unique(df,col):
  x=df.loc[df[col].apply(lambda x:len(x)>0)][col].explode().reset_index(drop=True)
  return set(list(x)),len(set(list(x))),x.value_counts().reset_index()

"""Since some columns have list as values like cast ,country we cant directly use unique,nunique,value_counts function directly so we defined above function for that"""

df['type'].unique()

"""Now we split the dataset into two parts movies and shows"""

movies=df.loc[df['type']=="Movie"].reset_index(drop=True)
movies.drop(columns="type",inplace=True)
movies.head()

shows=df.loc[df['type']=="TV Show"].reset_index(drop=True)
shows.drop(columns="type",inplace=True)
shows.head()

"""Here we are converting duration of movie to integer"""

movies['duration_in_minutes']=movies['duration'].apply(lambda x:int(x.split(" ")[0]))
movies.drop(columns="duration",inplace=True)
movies.head()

"""Here we are converting duration of show to integer"""

shows['Number of Seasons']=shows['duration'].apply(lambda x:int(x.split(" ")[0]))
shows.drop(columns="duration",inplace=True)
shows.head()

"""Now we will define some metrics"""

average_duration_of_each_movie=movies['duration_in_minutes'].mean()
print("average_duration_of_each_movie : ",np.round(average_duration_of_each_movie,2)," minutes ")

average_number_of_seasons_for_each_show=shows['Number of Seasons'].mean()
print("average_number_of_seasons_for_each_show : ",np.round(average_number_of_seasons_for_each_show,2)," sessons ")

avg_number_of_cast=np.round(df.loc[df['cast'].apply(lambda x:len(x))!=0]['cast'].apply(lambda x:len(x)).mean(),2)
print("avg_number_of_cast for a movie/show : ",avg_number_of_cast)

avg_number_of_cast=np.round(movies.loc[movies['cast'].apply(lambda x:len(x))!=0]['cast'].apply(lambda x:len(x)).mean(),2)
print("avg_number_of_cast for a movie : ",avg_number_of_cast)

avg_number_of_cast=np.round(shows.loc[shows['cast'].apply(lambda x:len(x))!=0]['cast'].apply(lambda x:len(x)).mean(),2)
print("avg_number_of_cast for a show : ",avg_number_of_cast)

"""If we observe above result generally more cast members are present in TV Shows rather than movies"""

avg_number_of_listed_in=np.round(df.loc[df['listed_in'].apply(lambda x:len(x))!=0]['listed_in'].apply(lambda x:len(x)).mean(),2)
print("avg_number_of_listed_ins for a movie/show : ",avg_number_of_listed_in)

avg_number_of_listed_in=np.round(movies.loc[movies['listed_in'].apply(lambda x:len(x))!=0]['listed_in'].apply(lambda x:len(x)).mean(),2)
print("avg_number_of_listed_ins for a movie : ",avg_number_of_listed_in)

avg_number_of_listed_in=np.round(shows.loc[shows['listed_in'].apply(lambda x:len(x))!=0]['listed_in'].apply(lambda x:len(x)).mean(),2)
print("avg_number_of_listed_ins for a show : ",avg_number_of_listed_in)

director_unique=get_unique(df,"director")
cast_unique=get_unique(df,"cast")
country_unique=get_unique(df,"country")
listed_in_unique=get_unique(df,"listed_in")

print("Number of unique directors : ",director_unique[1])
print("Number of unique cast members : ",cast_unique[1])
print("Number of unique countries : ",country_unique[1])
print("Number of unique listed_ins : ",listed_in_unique[1])

"""If we observe here rajiv chilaka directed 22 movies or shows"""

director_unique[2].head(10) #Top 10 directors by number of movies/shows directed

cast_unique[2].head(10) #Top 10 actors by number of movies/shows acted

country_unique[2].head(10) #Top 10 countries by number of movies/shows produced

listed_in_unique[2].head(10) #Top 10 Generes in movies/shows

df['rating'].value_counts().reset_index() #Top 10 ratings in movies/shows

movie_director_unique=get_unique(movies,"director")
movie_cast_unique=get_unique(movies,"cast")
movie_country_unique=get_unique(movies,"country")
movie_listed_in_unique=get_unique(movies,"listed_in")

print("Number of unique movie directors : ",movie_director_unique[1])
print("Number of unique movie cast members : ",movie_cast_unique[1])
print("Number of unique  movie countries : ",movie_country_unique[1])
print("Number of unique  movie listed_ins : ",movie_listed_in_unique[1])

movie_director_unique[2].head(10) #Top 10 directors by number of movies directed

movie_cast_unique[2].head(10) #Top 10 actors by number of movies acted

movie_country_unique[2].head(10) #Top 10 countries by number of movies produced

"""**Insight and Reason**

Netflix's strategy to acquire a large number of movies and TV shows from the United States is driven by Hollywood's global influence, the high production output and diversity of American content, strategic business decisions, and economic factors. These elements combined make U.S. content a cornerstone of Netflix's library, catering to both local and international audiences and ensuring sustained subscriber growth and engagement. By analyzing the data, we can observe these trends and understand the rationale behind Netflix's content acquisition strategy.

**Recommendation**

Foster strategic partnerships with major Hollywood studios and production companies to secure exclusive streaming rights for blockbuster movies and popular TV series.
"""

movie_listed_in_unique[2].head(10) #Top 10 geners in movies

movies['rating'].value_counts().reset_index() #Top 10 ratings in movies

show_director_unique=get_unique(shows,"director")
show_cast_unique=get_unique(shows,"cast")
show_country_unique=get_unique(shows,"country")
show_listed_in_unique=get_unique(shows,"listed_in")

print("Number of unique show directors : ",show_director_unique[1])
print("Number of unique show cast members : ",show_cast_unique[1])
print("Number of unique  show countries : ",show_country_unique[1])
print("Number of unique  show listed_ins : ",show_listed_in_unique[1])

show_director_unique[2].head(10) #Top 10 directors by number of shows directed

show_cast_unique[2].head(10) #Top 10 actorsby number of shows acted

show_country_unique[2].head(10) #Top 10 countries by number of shows produced

show_listed_in_unique[2].head(10)#Top 10 genres in shows

shows['rating'].value_counts() #Top 10 ratings in shows

"""Let us make pie chart on Number of Movies vs Tv Shows by netflix"""

plt.figure(figsize=(10,6))
plt.pie(df['type'].value_counts(),labels=df['type'].value_counts().index,autopct="%.2f%%")
plt.title("Movies vs Shows")
plt.show()

"""**Insight and Reason**

The observation that there are more movies than TV shows in a Netflix dataset can be attributed to several factors related to content acquisition, audience preferences, and platform strategy:

Variety and Global Appeal
Broad Content Selection: Movies span various genres, languages, and cultural backgrounds, appealing to a wide audience globally. This diversity allows Netflix to cater to different viewer preferences and maximize its content library's appeal.

Global Licensing: Netflix acquires movies from around the world through licensing agreements with studios and distributors. This allows them to offer a broad range of content to their global subscriber base.

**Recommendation**

Predict how this balance might evolve over time based on emerging industry trends and invest accordingly
"""

plt.figure(figsize=(12,8))
d=movie_country_unique[2].head(10)
sns.barplot(x="country",y="count",data=d)
plt.xlabel("Country")
plt.ylabel("Number of movies produced")
plt.title("Top 10 countries by number of movies produed")
plt.show()

plt.figure(figsize=(14,8))
d=show_country_unique[2].head(10)
sns.barplot(x="country",y="count",data=d)
plt.xlabel("Country")
plt.ylabel("Number of shows produced")
plt.title("Top 10 countries by number of shows produed")
plt.show()

"""**Insight and Reason**

If observe the above two plots we can observe netflix has aquired more movies from some countries but less number of shows from them

For example from india netflix has aquired second most number of movies among all countries but it aquired less number of movies compared to other countries.This can be due to following reasons:

Netflix's strategy to acquire more movies than TV shows from India is driven by historical and cultural preferences, economic efficiencies, market demand, and strategic business goals. This approach allows Netflix to tap into the vast and diverse Indian film industry, cater to local and global audiences, and strengthen its market position. By analyzing the data, we can observe these trends and validate the underlying reasons for Netflix's content acquisition strategy.

**Recommendation**

Forecast how Netflix’s acquisition of Indian movies might evolve in the future.

Will Netflix continue to invest in Indian cinema, and how might this impact its global market position?

Anticipate trends in viewer preferences and consumption patterns in the streaming industry.
"""

year=df['date_added'].dt.year
year.value_counts().reset_index().sort_values("date_added")

year=df['date_added'].dt.year
plt.figure(figsize=(12,8))
plt.xlabel("year")
plt.ylabel("Number of movies/shows aquired by netflix")
sns.histplot(year,kde=True,bins=8)
plt.show()

"""**Insight and Reason**

If we observe number of shows/movies aquired by netflix have decreased from 2019 this can be due to

1.COVID-19 Pandemic:

Global Impact on Production: The COVID-19 pandemic caused significant disruptions in film and TV show production worldwide, leading to delays and halts. Many projects that were slated for release or acquisition in 2020 and 2021 were postponed.

Safety Protocols: Even as productions resumed, new safety protocols and regulations slowed down the production process, reducing the overall output of new content.

2.Market Saturation and Competition


New Streaming Services: The emergence and growth of other streaming platforms like Disney+, HBO Max, Apple TV+, and Amazon Prime Video have intensified competition for acquiring content
"""

month=movies['date_added'].dt.month_name()
plt.figure(figsize=(12,8))
plt.xlabel("month")
plt.ylabel("Number of movies/shows aquired by netflix")
sns.barplot(x=month.value_counts().index,y=month.value_counts())
plt.show()

"""**Insight and Reason**

The observation that more movies are released by Netflix in July and April months in a Netflix dataset could be influenced by several factors related to content strategy, industry trends, and audience behavior. Here are some potential reasons:

Seasonal Trends and Holidays
Summer Releases: July is often considered a peak period for movie releases in general, as it coincides with summer vacations in many countries. Netflix may strategically release more content during this time to capture increased viewership.

Spring Releases: April could also see increased releases due to spring breaks and holidays in various regions, leading to higher potential viewership.
"""

month=shows['date_added'].dt.month_name()
plt.figure(figsize=(12,8))
plt.xlabel("month")
plt.ylabel("Number of movies/shows aquired by netflix")
sns.barplot(x=month.value_counts().index,y=month.value_counts())
plt.show()

"""**Insight and Reason**

The trend of launching more shows in November and December by Netflix can be attributed to several strategic and practical considerations:

Holiday Season and Viewer Behavior:

Holiday Viewing: November and December coincide with major holidays such as Thanksgiving, Christmas, and New Year's Eve. During these festive periods, people often have more leisure time and are likely to engage in binge-watching. Netflix strategically releases new shows to capitalize on increased viewer engagement during these months.

Cultural and Regional Preferences: In many cultures, the holiday season is a time for family gatherings and indoor activities. Releasing new shows during this period aligns with cultural norms and viewer behavior patterns, maximizing viewership.
"""

weekday=movies['date_added'].dt.day_name()
plt.figure(figsize=(12,8))
plt.xlabel("day of the week")
plt.ylabel("Number of movies/shows aquired by netflix")
sns.barplot(x=weekday.value_counts().index,y=weekday.value_counts())
plt.show()

"""**Insight and Reason**

Netflix launches movies or shows on friday due to

Weekend Viewing: Fridays mark the beginning of the weekend for many people globally. Netflix capitalizes on this by releasing new content when viewers are more likely to have leisure time and engage in binge-watching.

Binge-Watching Culture: Many Netflix subscribers prefer to watch multiple episodes or movies in one sitting, especially over the weekend. Releasing new content on Fridays encourages binge-watching behavior and increases viewer retention.
"""

x=shows.loc[shows["date_added"].dt.month==12]['date_added'].dt.day
plt.xlabel("day")
plt.ylabel("count")
sns.histplot(x)

"""**Insight and Reason**


The timing of show launches on Netflix, particularly why more shows are launched during December 10-15 compared to December 20-25, can be influenced by several strategic considerations:

1.Lead Time and Marketing Strategy
Holiday Promotions: Shows launched during December 10-15 have more lead time before Christmas and New Year's Eve. This timing allows Netflix to build anticipation through marketing campaigns, generating buzz and maximizing visibility before the holiday season peaks.

2.Avoiding Holiday Rush: Releasing shows earlier in December (around December 10-15) helps Netflix avoid the intense competition and saturation of content releases that typically occur closer to Christmas (December 20-25). By launching earlier, Netflix can capture viewer attention before they become overwhelmed with holiday activities and distractions.

**Recommendation**

If we have observed above insights Mid of december is best time to launch a TV Show
"""

plt.figure(figsize=(12,8))
plt.title("distribution of release year")
sns.boxplot(movies['release_year'])

"""**Insight and Reason**

The observation that most movies released in a Netflix dataset are after the year 2000 can be attributed to several factors related to the evolution of the film industry, content acquisition strategies by streaming platforms like Netflix, and the availability and popularity of digital content. Here are some reasons why this might be the case:

Digital Transformation of Content
Shift to Digital Distribution: Beginning in the late 1990s and early 2000s, there was a significant shift in the film industry towards digital distribution formats. This made it easier for newer movies to be distributed and streamed online, including through platforms like Netflix.

Availability of Digital Copies: Many older movies were originally distributed on physical formats like VHS tapes or DVDs, and they were gradually digitized and made available on streaming platforms post-2000.

**Recommendation**

Consider the implications for user experience and satisfaction with the content library.

How does the availability of recent movies contribute to personalized recommendations and user retention?

Are there opportunities to further enhance the diversity or depth of recent movie offerings?
"""

current_year = pd.Timestamp.now().year
start_year = current_year - 30  # 30 years ago
end_year = current_year - 20    # 20 years ago
movie_counts = df[df['release_year'].between(start_year, end_year)].groupby('release_year').size()
plt.figure(figsize=(10, 6))
plt.plot(movie_counts.index, movie_counts.values, marker='o', linestyle='-', color='b')
plt.title('Number of Movies Released per Year ({} to {})'.format(start_year, end_year))
plt.xlabel('Year')
plt.ylabel('Number of Movies Released')
plt.grid(True)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""**Insight and Reason**

If we observe the above plot we can see that number of movies aquired from 1994 t0 2004 shown increasing trend.This can be due to

Growth of the Film Industry
Expansion of Production Studios: Over the past few decades, there has been a proliferation of production studios globally, leading to an increase in the number of movies being produced each year.

Globalization: The film industry has become more globalized, with production companies from various countries contributing to the overall increase in movie releases.

**Recommendation**

Analyze how this historical trend informs Netflix's current content strategy.

Consider how Netflix might leverage historical acquisition patterns to guide future content investments.

Discuss implications for subscriber retention, market positioning, and competitive advantage in the streaming landscape.
"""

current_year = pd.Timestamp.now().year
start_year = movies['date_added'].dt.year.max() - 8
end_year = movies['date_added'].dt.year.max()
movie_counts =movies[movies['date_added'].dt.year.between(start_year, end_year)]['date_added'].dt.year.value_counts().reset_index().sort_values("date_added")
plt.figure(figsize=(10, 6))
plt.plot(movie_counts['date_added'], movie_counts['count'] ,marker='o', linestyle='-', color='b')
plt.title('Number of Movies Released per Year ({} to {})'.format(start_year, end_year))
plt.xlabel('Year')
plt.ylabel('Number of Movies Released')
plt.grid(True)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

current_year = pd.Timestamp.now().year
start_year = shows['date_added'].dt.year.max() - 8
end_year = shows['date_added'].dt.year.max()
show_counts =shows[shows['date_added'].dt.year.between(start_year, end_year)]['date_added'].dt.year.value_counts().reset_index().sort_values("date_added")
plt.figure(figsize=(10, 6))
plt.plot(show_counts['date_added'], show_counts['count'] ,marker='o', linestyle='-', color='b')
plt.title('Number of shows Released per Year ({} to {})'.format(start_year, end_year))
plt.xlabel('Year')
plt.ylabel('Number of shows Released')
plt.grid(True)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""**Insight and Reason**

Netflix's shift towards focusing more on TV shows than movies in recent years can be attributed to several strategic and market-driven factors:

1. Audience Engagement and Viewing Behavior
Changing Viewer Preferences: There has been a noticeable trend towards binge-watching TV series rather than watching movies in one sitting. TV shows provide longer engagement periods and can keep subscribers subscribed for longer durations.

Global Appeal: TV shows often have broader international appeal compared to movies, as they can cater to diverse cultural and linguistic preferences with serialized storytelling.

2. Content Production Economics
Cost Efficiency: Producing TV shows can be more cost-effective than producing movies, especially when considering the duration of viewer engagement per dollar spent on content production.

Long-Term Content Strategy: TV shows allow for the development of a dedicated fan base and can generate ongoing interest over multiple seasons, enhancing long-term subscriber retention.
"""

plt.figure(figsize=(10, 6))
plt.hist(movies['duration_in_minutes'], bins=30, color='blue', edgecolor='black')
plt.title('Distribution of Content Duration on Netflix')
plt.xlabel('Duration (minutes)')
plt.ylabel('Frequency')
plt.grid(True)
plt.tight_layout()
plt.show()

"""**Insight and Reason**

The prevalence of movies around 100 minutes in duration on Netflix likely reflects a combination of audience preferences, industry norms, production economics, and platform strategies aimed at optimizing viewer satisfaction and content diversity. While there are movies of various lengths available on Netflix, the popularity of movies around this duration indicates a balance between narrative completeness and viewer accessibility in the streaming era.
"""

season=shows['Number of Seasons']
plt.figure(figsize=(12,8))
plt.xlabel("day of the week")
plt.ylabel("Number of seasons of a show in netflix")
sns.barplot(x=season.value_counts().index,y=season.value_counts())
plt.show()

"""**Insight and Reason**

The predominance of TV shows with 1 or 2 seasons on Netflix reflects strategic decisions influenced by viewer behavior, production economics, licensing availability, and platform strategy. While there are exceptions with longer-running series and original productions, the focus on shorter series initially allows Netflix to manage risks, optimize viewer engagement, and maintain a dynamic content catalog that appeals to global audiences.







"""

plt.figure(figsize=(10, 6))
df['rating'].value_counts().plot(kind='bar', color='blue')
plt.title('Distribution of Ratings on Netflix')
plt.xlabel('Rating')
plt.ylabel('Number of Titles')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 6))
movies['rating'].value_counts().plot(kind='bar', color='blue')
plt.title('Distribution of movie Ratings on Netflix')
plt.xlabel('Rating')
plt.ylabel('Number of Titles')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 6))
shows['rating'].value_counts().plot(kind='bar', color='blue')
plt.title('Distribution of show Ratings on Netflix')
plt.xlabel('Rating')
plt.ylabel('Number of Titles')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""**Insight and Reason**

The prevalence of TV-MA (Mature Audience) and TV-14 rating movies/shows on Netflix can be attributed to several strategic and audience-related factors:

Targeting Older Audiences: TV-MA and TV-14 ratings cater to older audiences who prefer content with mature themes, stronger language, and more intense or graphic content. Netflix's data analytics likely show a significant portion of their subscriber base falls into these demographics.

Diverse Content Preferences: Offering a variety of content ratings ensures Netflix can appeal to a broad spectrum of viewers, including those seeking more adult-oriented programming.

The prevalence of TV-PG ratings in TV shows compared to movies in a Netflix dataset can be influenced by several factors related to content categorization, viewer demographics, and platform strategy. Here are some possible reasons for this observation:

Target Audience: TV-PG ratings are typically designed for a broader audience, including children and families. TV shows often cater to diverse age groups, including younger viewers, where content is more likely to be rated as TV-PG to ensure broader accessibility.

Content Variety: Netflix may prioritize TV shows with TV-PG ratings to cater to family viewing preferences and ensure a balanced content library that appeals to a wide range of viewers.

**Recommendations**

Regulatory and Cultural Factors: Consider potential regulatory implications and cultural sensitivities associated with mature content ratings.

Netflix's approach to content moderation and compliance with regional standards.
Content Strategy Evolution: Predict how the prevalence of these ratings might evolve over time based on viewer demographics and market trends.

Shifts in audience preferences and global expansion strategies.
"""

plt.figure(figsize=(10, 6))
sns.barplot(x=movie_listed_in_unique[2].head(10)['listed_in'],y=movie_listed_in_unique[2].head(10)['count'], color='blue')
plt.title('Distribution of top 10 Movie Genres on Netflix')
plt.xlabel('Genre')
plt.ylabel('Number of Titles')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""Here we can observe international movies,dramas,comedies are leading may be due to global appealing content

**Recommendation**

Continued Investment: Recommend continued investment in diverse international content to maintain and expand global audience engagement.

Enhanced Localization: Suggest enhancements in localization strategies (subtitles, dubbing, regional partnerships) to further enhance global appeal and market penetration.
"""

plt.figure(figsize=(10, 6))
sns.barplot(x=show_listed_in_unique[2].head(10)['listed_in'],y=show_listed_in_unique[2].head(10)['count'], color='blue')
plt.title('Distribution of top 10 Show Genres on Netflix')
plt.xlabel('Genre')
plt.ylabel('Number of Titles')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""Here we can observe international tv shows,tv dramas,tv comedies are leading may be dy eto global appealing content"""

d=df.loc[df['country'].apply(lambda x:len(x)!=0)][['type','country']]
d=d.explode('country')
d=d.loc[d['country'].isin(country_unique[2].head()['country'])]

counts = d.groupby(['country', 'type']).size().unstack(fill_value=0)
counts

plt.figure(figsize=(12, 8))
counts_percentage = counts.div(counts.sum(axis=1), axis=0) * 100
# Plot stacked bar chart
counts_percentage.plot(kind='bar', stacked=True,colormap='viridis')

plt.title('Distribution of Movies and TV Shows for top 5 countries')
plt.xlabel('Country')
plt.ylabel('Count')
plt.legend(title='Type', labels=['Movie', 'TV Show'])
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""**Insight and Reason**

If we observe  the above plot there is good balance between shows and movies in countries like UK and US but in india it looks imbalanced

The structure of the Indian entertainment industry is such that TV shows are often produced for traditional television networks rather than streaming platforms. While this is changing with the rise of streaming services, the focus on movies remains strong.

**Recommendation**

Content Acquisition and Production:

Recommend adjustments in Netflix's content strategy for India to achieve a more balanced offering.
Suggest increasing investment in TV show production or acquiring more diverse TV content that resonates with Indian audiences.

User Experience and Engagement:

Propose enhancements to Netflix's recommendation algorithms to better cater to regional content preferences.
Explore opportunities for promoting TV shows more effectively to balance the content mix in India.
"""

d=df[['type','rating']]
counts = d.groupby(['rating', 'type']).size().unstack(fill_value=0)
plt.figure(figsize=(14, 8))
counts_percentage = counts.div(counts.sum(axis=1), axis=0) * 100
# Plot stacked bar chart
counts_percentage.plot(kind='bar', stacked=True,colormap='viridis')

plt.title('Distribution of Movies and TV Shows for different rated movies/shows')
plt.xlabel('Country')
plt.ylabel('Count')
plt.legend(title='Type', labels=['Movie', 'TV Show'])
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""**Insight and Reason**

If we observe some ratings like R,G and PG are completely dominated by movies while in some ratings like Tv-Y and TV-Y7 Tv shows are dominating

R-Rated Movies: Often include mature content, such as intense violence, strong language, and adult themes. Such content is more commonly explored in movies than in TV shows, given the shorter format and more significant impact that can be delivered in a film.
G and PG Movies: These are family-friendly or child-friendly movies that are designed to be suitable for all or most audiences. Animated movies, family films, and children's films often fall into these categories, and movies have traditionally been a significant medium for delivering such content.

TV-Y (All Children) and TV-Y7 (Directed to Older Children) ratings are designed specifically for children. These ratings ensure that content is appropriate for young viewers, including educational shows, cartoons, and other children’s programming.

**Recommendation**

Compare Netflix's distribution with other streaming platforms or traditional media.
How do competitors like Disney+ or HBO Max handle content distribution across different ratings?
What does this insight reveal about evolving viewer preferences and consumption habits in the streaming landscape?
"""

d=df[['type','release_year']]

plt.figure(figsize=(10, 6))

# Create a box plot with hue using seaborn
sns.boxplot(x='type', y='release_year', data=d, hue='type')

# Formatting
plt.title('Box Plot of year released by Type (Movie vs TV Show)')
plt.xlabel('Type')
plt.ylabel('year released')
plt.legend(title='Type', loc='best')  # Adjust legend location if needed
plt.grid(True)
plt.tight_layout()
plt.show()

"""**Insight and Reason**
If we observe the above plot average release year for TV show is more than movies.This can be due to

TV Licensing: Licensing agreements for TV shows often focus on recent seasons and series, as networks and producers aim to capitalize on current viewer interest. This results in a higher proportion of recent TV shows being available on streaming platforms.

Movie Licensing: Movie licensing deals can include a mix of recent blockbusters, older classics, and everything in between. This diversity in licensing agreements impacts the average release year for movies.

**Recommendation**

Predict how this trend might evolve in the future, considering shifts in content consumption habits and technological advancements:

Will the gap between average release years for movies and TV shows narrow or widen with the growth of streaming and on-demand viewing?
"""

d=movies.explode('country')
d=d.loc[d['country'].isin(movie_country_unique[2].head(5)['country'])]
d=d.loc[d['rating'].isin(d['rating'].value_counts().head().index)]

rating_counts = d.groupby(['country', 'rating']).size().unstack(fill_value=0)
rating_counts

plt.figure(figsize=(12, 8))
counts_percentage = (rating_counts.T.div(rating_counts.sum(axis=1))*100).T

counts_percentage.plot(kind='bar', stacked=True, colormap='tab20', figsize=(15, 10))
plt.title('Top 5 Censorship Rating vs Top 5 Country in Netflix Movies')
plt.xlabel('Country')
plt.ylabel('Count of Ratings')
plt.legend(title='Rating', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

"""**Insight and Reason**

If we observe above plots most of movies produced by india are in TV-14 and TV-MA rated while countries US,UK,Canada had good proporation of R rated movies

**Recommendations**

Provide actionable recommendations based on the insights gained:
Consider expanding content partnerships or production efforts in regions with high demand for specific ratings.

Enhance content diversity strategies to cater to varied audience preferences across different markets.

Continuously monitor and adapt content offerings based on evolving viewer behavior and regulatory landscapes.
"""

d=shows.explode('country')
d=d.loc[d['country'].isin(show_country_unique[2].head(5)['country'])]
d=d.loc[d['rating'].isin(d['rating'].value_counts().head().index)]

rating_counts = d.groupby(['country', 'rating']).size().unstack(fill_value=0)
rating_counts

plt.figure(figsize=(12, 8))
counts_percentage = (rating_counts.T.div(rating_counts.sum(axis=1))*100).T

counts_percentage.plot(kind='bar', stacked=True, colormap='tab20', figsize=(15, 10))
plt.title('Top 5 Censorship Rating vs Top 5 Country in Netflix TV Shows')
plt.xlabel('Country')
plt.ylabel('Count of Ratings')
plt.legend(title='Rating', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

"""**Insight and Reason**

If we observe above plots most of shows produced by south korea are in TV-14 and TV-MA rated while countries UKa had good proporation of PG rated shows

**Recommendations**

Predict how these rating distributions might evolve over time based on industry trends and changing viewer preferences.

Will South Korean productions expand into different rating categories as their global reach grows?

How might the UK's content strategy adapt to changing viewer expectations and regulatory standards?
"""

d=movies.explode('country')
for i, country in enumerate(movie_country_unique[2]['country'].head()):
    plt.subplot(3, 2, i+1)
    a=d[d['country']==country]
    a=a.explode(['listed_in'])
    country_data = a['listed_in'].value_counts().head().reset_index()
    sns.barplot(x='count', y='listed_in', data=country_data, palette='tab20')
    plt.title(f'Top Genres in movies  {country}')
    plt.xlabel('Count')
    plt.ylabel('Genre')

plt.tight_layout()
plt.show()

"""**Insights**

If we observe above plots dramas is dominating in US and UK,international movies dominating in India and France ,comedies in canada

**Recommendations**

Predict how these genre preferences might evolve over time and how Netflix should adapt.

Will there be shifts in genre popularity based on global trends or socio-economic factors?

How can Netflix innovate to maintain or expand its audience base in each region?
"""

d=shows.explode('country')
for i, country in enumerate(show_country_unique[2]['country'].head()):
    plt.subplot(3, 2, i+1)
    a=d[d['country']==country]
    a=a.explode(['listed_in'])
    country_data = a['listed_in'].value_counts().head().reset_index()
    sns.barplot(x='count', y='listed_in', data=country_data, palette='tab20')
    plt.title(f'Top Genres in shows  {country}')
    plt.xlabel('Count')
    plt.ylabel('Genre')

plt.tight_layout()
plt.show()

"""**Insights**

If we observe above plots interantional tv shows are dominating  in japan and south korea,kids TV in canada,TV comedies in US,British TV Shows in UK

**Recommendations**

Competitive Landscape: Compare Netflix's dominance in specific genres across regions with competitors or traditional broadcasters.
Identify strengths and potential areas for growth based on regional content preferences.
"""

d=movies[['country','duration_in_minutes']]
d=d.explode('country')
d=d.loc[d['country'].isin(movie_country_unique[2].head()['country'])]
plt.figure(figsize=(10, 6))

# Create a box plot with hue using seaborn
sns.boxplot(x='country', y='duration_in_minutes', data=d, hue='country')

# Formatting
plt.title('Box Plot of movie duration added for top 5 countries')
plt.xlabel('Type')
plt.ylabel('year added')
plt.legend(title='Type', loc='best')  # Adjust legend location if needed
plt.grid(True)
plt.tight_layout()
plt.show()

"""**Insight**

If we observe the above plot average duration of movie is more in india compared to countries like US,UK,France,Canada

**Outlier**

If we observe the above plot some movies have very less duration less than 50 minutes which has to be considered as outliers
"""

d=shows[['country','Number of Seasons']]
d=d.explode('country')
d=d.loc[d['country'].isin(show_country_unique[2].head()['country'])]
plt.figure(figsize=(10, 6))

# Create a box plot with hue using seaborn
sns.barplot(x='country', y='Number of Seasons', data=d, hue='country')

# Formatting
plt.title('Bar plot for number of seasons for a show top 5 countries')
plt.xlabel('Type')
plt.ylabel('Number of Sesons')
plt.legend(title='Type', loc='best')  # Adjust legend location if needed
plt.grid(True)
plt.tight_layout()
plt.show()

"""**Insight**

If we observe the above plot average number of seasons of TV Show is more in canada compared to countries like US,UK,japan,soth korea
"""

d=shows[['country','release_year']]
d=d.explode('country')
d=d.loc[d['country'].isin(show_country_unique[2].head()['country'])]
plt.figure(figsize=(10, 6))

# Create a box plot with hue using seaborn
sns.boxplot(x='country', y='release_year', data=d, hue='country')

# Formatting
plt.title('Box Plot of release year for top 5 countries')
plt.xlabel('Type')
plt.ylabel('year added')
plt.legend(title='Type', loc='best')  # Adjust legend location if needed
plt.grid(True)
plt.tight_layout()
plt.show()

"""**Insight**

If we observe above box plot japan has more old TV shows compared to UK,US,south korea,canada

**Recommendation**

Discuss potential reasons for this disparity:
Cultural Influence: Explore how cultural factors in Japan might prioritize preservation and accessibility of older TV shows.

Content Licensing and Acquisition: Analyze how Netflix’s content acquisition strategies differ across regions, potentially affecting the availability of newer versus older content.

**Outlier**

If we observe above plot there are some movies which are released before 2000 are aquired by netflix can be outliers
"""

correlation_matrix = movies[['release_year','duration_in_minutes']].corr()

# Create a heatmap
plt.figure(figsize=(10, 6))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=.5)
plt.title('Heatmap of Correlation between release year and duration in Netflix Dataset')
plt.show()

"""**Insight**

If we observe corrleation matrix it seems like there is negative corrleation between year released and duration of movie which can be intepreted as now movies are coming with shorter duration for better quality
"""

d=movies[['rating','release_year']]
d=d.loc[d['rating'].isin(d['rating'].value_counts().head().index)]
plt.figure(figsize=(10, 6))

# Create a box plot with hue using seaborn
sns.boxplot(x='rating', y='release_year', data=d, hue='rating')

# Formatting
plt.title('Box Plot of release year for top 5 rated movies')
plt.xlabel('Type')
plt.ylabel('year added')
plt.legend(title='Type', loc='best')  # Adjust legend location if needed
plt.grid(True)
plt.tight_layout()
plt.show()

"""**Insight**

If we observe TV-MA ,TV-PG rated movies are being released more recently compared to TV-14,PG-13,R rated movies since thier median is higher compared to **others**

**Recommendations**

Content Strategy: Discuss potential reasons why TV-MA and TV-PG rated movies are more prevalent in recent releases.

Netflix's strategic focus on expanding family-friendly or mature content categories.

Shifts in viewer demographics or market demand influencing production and acquisition strategies.

Market Positioning: Evaluate how this trend impacts Netflix's competitive positioning and subscriber engagement.
Alignment with viewer preferences and content consumption patterns

**Outlier**

If we observe above plot there are some movies which are released before 1990 are aquired by netflix can be outliers
"""

d=movies[['rating','date_added']]
d['year']=d['date_added'].dt.year
d=d.loc[d['rating'].isin(d['rating'].value_counts().head().index)]
plt.figure(figsize=(10, 6))

# Create a box plot with hue using seaborn
sns.boxplot(x='rating', y='year', data=d, hue='rating')

# Formatting
plt.title('Box Plot of year added for top 5 rated movies')
plt.xlabel('Type')
plt.ylabel('year added')
plt.legend(title='Type', loc='best')  # Adjust legend location if needed
plt.grid(True)
plt.tight_layout()
plt.show()

"""**Insight**

If we observe PG-13 rated shows are being added more recently compared to TV-14,TV-MA,TV-PG,R rated ones

**Recommendations**

Future Content Planning: Recommend how Netflix can capitalize on this trend in future content planning and acquisition.

Continuously monitor viewer preferences and adapt content strategy to meet evolving demands for PG-13 content.

Balanced Content Portfolio: Emphasize the importance of maintaining a balanced content portfolio across various ratings to cater to diverse audience preferences.

**Outlier**

If we observe above plot there are some movies which are added before 2015 by netflix can be outliers
"""

d=movies[['listed_in','date_added']]
d['year']=d['date_added'].dt.year
d=d.explode('listed_in')
d=d.loc[d['listed_in'].isin(d['listed_in'].value_counts().head().index)]

plt.figure(figsize=(10, 6))

# Create a box plot with hue using seaborn
sns.boxplot(x='listed_in', y='year', data=d, hue='listed_in')

# Formatting
plt.title('Box Plot of year added for top 5 genre movies')
plt.xlabel('Type')
plt.ylabel('year added')
plt.legend(title='Type', loc='best')  # Adjust legend location if needed
plt.grid(True)
plt.tight_layout()
plt.show()

"""**Insight**

If we observe above plot netflix havent added more  documentries in recent years  compared to other gener like dramas,comedies

**Recommendations**

Content Acquisition: Recommend strategies to enhance Netflix's documentary offerings if they are deemed strategically important.

Increase investment in original documentary production or exclusive licensing deals.

Collaborate with renowned filmmakers or documentary production houses to expand content library.

Viewer Engagement: Suggest initiatives to boost viewer engagement with documentaries through improved recommendation algorithms or curated collections.

**Outlier**

If we observe above plot there are some movies which are added before 2015 by netflix can be outliers
"""

d=movies[['listed_in','duration_in_minutes']]
d=d.explode('listed_in')
d=d.loc[d['listed_in'].isin(d['listed_in'].value_counts().head().index)]

plt.figure(figsize=(10, 6))

# Create a box plot with hue using seaborn
sns.boxplot(x='listed_in', y='duration_in_minutes', data=d, hue='listed_in')

# Formatting
plt.title('Box Plot of duration for top 5 rated movies')
plt.xlabel('Type')
plt.ylabel('year added')
plt.legend(title='Type', loc='best')  # Adjust legend location if needed
plt.grid(True)
plt.tight_layout()
plt.show()

"""**Insight**

If we observe dramas,international movies are of more duration compared  to documnentries
"""